# Generated by Django 5.2.7 on 2025-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(choices=[('mon/wed/fri', 'пн/ср/пт'), ('tue/thu/sat', 'вт/чт/сб'), ('sat/sun', 'сб/вс')], max_length=50, null=True)),
                ('age', models.CharField(default='Все возраста', max_length=100)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='groups', to='account.user')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
