# Generated by Django 5.2.7 on 2025-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.CharField(default='Все', max_length=100),
        ),
    ]
