# Generated by Django 6.0 on 2025-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
