# Generated by Django 5.2.7 on 2025-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('child', 'ребонок'), ('parent', 'родитель'), ('student', 'ученик'), ('admin', 'админ')], default='user', max_length=20),
        ),
    ]
