# Generated by Django 5.2.7 on 2025-11-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('child', 'ребёнок'), ('parent', 'родитель'), ('student', 'ученик'), ('admin', 'админ')], default='user', max_length=20),
        ),
    ]
