# Generated by Django 6.0 on 2025-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('child', 'ребёнок'), ('parent', 'родитель'), ('student', 'ученик'), ('admin', 'админ')], default='student', max_length=20),
        ),
    ]
