# Generated by Django 5.2.7 on 2025-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lesson_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
