# Generated by Django 5.2.7 on 2025-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_lesson_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='attedance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
