# Generated by Django 5.2.7 on 2025-11-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_attedance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='attedance',
            new_name='attendance',
        ),
    ]
