# Generated by Django 6.0 on 2025-12-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_role'),
        ('subscription', '0004_rename_attedance_subscription_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='account.user'),
        ),
    ]
